### PR TITLE
Eslint && NSP task

### PR DESCRIPTION
**Pull request by zckrs**

### CODE REVIEW

**Comment by Swiip** [comment]
:+1: to have precise git conf.

But I see a problem: I kept the possibility open 'till now to use generators ng1, ng2 and React directly bypassing the webapp generator and the framework question.

If you add features in this generator, bypassing it will remove features...

**Comment by zckrs** [comment]
Understood but we should duplicate git subgenerator ? or create a `generator-fountain-git` ?

**Comment by Swiip** [comment]
I would have put this in generator-fountain-gulp:git perhaps. generator-fountain-gulp is the only central generator that any configuration use.

**Comment by zckrs** [comment]
PR updated.

https://github.com/FountainJS/generator-fountain-gulp/pull/4

**Pull request merged**
